




.build/nano328/src/monitorCC3D.cpp : src/monitorCC3D.ino
	@mkdir -p .build/nano328/src
	@echo [93msrc/monitorCC3D.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/nano328/src/monitorCC3D.cpp
	@true

