







	



.build/uno/SoftwareSerial/SoftwareSerial.d : /usr/share/arduino/libraries/SoftwareSerial/SoftwareSerial.cpp
	@mkdir -p .build/uno/SoftwareSerial
	@/usr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=103 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/WiFi -I/usr/share/arduino/libraries/WiFi/utility -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/Esplora -I/usr/share/arduino/libraries/LiquidCrystal  -MM $^ > $@
	
	@printf ".build/uno/SoftwareSerial/SoftwareSerial.d .build/uno/SoftwareSerial/" | cat - $@ > $@~ && mv $@~ $@



.build/uno/SoftwareSerial/dependencies.d : .build/uno/SoftwareSerial/SoftwareSerial.d
	@echo [96mScanning dependencies of SoftwareSerial[0m
	@mkdir -p .build/uno/SoftwareSerial
	@cat $^ > $@;

all : .build/uno/SoftwareSerial/dependencies.d
	@true

