




.build/uno/src/monitorCC3D.cpp : src/monitorCC3D.ino
	@mkdir -p .build/uno/src
	@echo [93msrc/monitorCC3D.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^

.build/uno/src/UAVTalk.cpp : src/UAVTalk.ino
	@mkdir -p .build/uno/src
	@echo [93msrc/UAVTalk.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/uno/src/monitorCC3D.cpp .build/uno/src/UAVTalk.cpp
	@true

